name: expandable_sliver_list
description: A sliver list that can be hidden or shown
version: 1.0.0+1
homepage: https://github.com/TNorbury/flutter_expandable_sliver_list
repository: https://github.com/TNorbury/flutter_expandable_sliver_list
issue_tracker: https://github.com/TNorbury/flutter_expandable_sliver_list/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.2.0
  flutter_test:
    sdk: flutter

flutter:

