name: expandable_sliver_list
description: A sliver list that can be hidden or shown
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.2.0
  flutter_test:
    sdk: flutter

flutter:

